version: 2.1
  jobs:
    build:
      docker:
        - image: circleci/ruby:2.6.5-node-browsers # ジョブのコマンドが実行されるプライマリ コンテナ
      steps:
        - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
        - run: puts "hello world" # `echo` コマンドを実行します